export const vocabulary: any = {
  name: 'Name',
  email: 'E-Mail',
  phone: 'Telefonnummer',
  file: 'Datei',
  message: 'Nachricht',
  gender: 'Gender',
  address: 'Adresszeile 1',
  city: 'Stadt',
  country: 'Land',
  zip_code: 'Postleitzahl',
  travellers: 'Reisende',
  sender: 'Die Daten der Person mit, die den Geschenkgutschein versendet',
  title: 'Anrede',
  recipient: 'Empfängername',
  from: 'Gutschein vom',
  value: 'Wert des Gutscheins ein Muss mehr als 50 CHF betragen',
  recepientEmail: 'E-Mail',
  adults: 'Erwachsene',
  arrivalTo: 'Ankunft in',
  departFrom: 'Abreise von',
  boardType: 'Verpflegungsart ',
  earliestDeparture: 'Früheste Abreise',
  latestReturn: 'Späteste Rückreise',
  totalTripBudget: 'Reisepreis insgesamt',
  transferType: 'Übertragung',
  travellersData:
    'Vor- und Nachname, Staatsangehörigkeit, Geschlecht, Geburtsdatum, Adresszeile 1, Adresszeile 2',
}
